language: node_js
node_js:
  - 6
  - 8
  - 10
  - node
git:
  depth: 1
  quiet: true
env:
  - NODE_ENV=test FORCE_COLOR=1 CODECOV_TOKEN=57505d49-e049-41f6-827c-6785f48bfcf3
cache:
  yarn: true
  directories:
    - 'node_modules'
script:
  - yarn test
after_success:
  - yarn global add codecov@^3
  - codecov
